apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ra2ce-ptk-
  annotations:
    title: RA2CE PTK
    description: PTK - RA2CE - PTK
spec:
  entrypoint: complete
  serviceAccountName: test
  imagePullSecrets:
    - name: regcred

  templates:
    - name: complete
      steps:
      - - name: ptk-preprocessing
          template: ptk
          arguments:
            parameters:
            - name: ptk_arguments
              value: ""
      - - name: read-models
          template: read-models
      - - name: ra2ce
          template: ra2ce
          arguments:
            parameters:
            - name: model
              value: "{{item}}"
          withParam: "{{steps.read-models.outputs.result}}"
      - - name: ptk-analyse
          template: ptk
          arguments:
            parameters:
            - name: ptk_arguments
              value: "-performed"

    - name: only-ptk
      steps:
      - - name: ptk
          template: ptk
          arguments:
            parameters:
            - name: ptk_arguments
              value: ""

    - name: ptk
      inputs:
        parameters:
          - name: ptk_arguments
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: os
          operator: Equal
          value: windows
          effect: NoSchedule
      container:
        image: deltares/ptk:2-3-5
        command:
          - 'powershell'
        # args:
        #   - Start-Sleep -Seconds 1000
        args:
          - aws s3 sync s3://bucket-deltares-et/RA2CE-PTK c:/data/RA2CE-PTK; & cd C:\data\RA2CE-PTK\PTK_Cloud; & cmd /c 'C:\Program Files (x86)\Deltares\Probabilistic toolkit\Deltares.Probabilistic.Console.exe' {{inputs.parameters.ptk_arguments}} run_ra2ce.tkx; & aws s3 sync c:/data/RA2CE-PTK s3://bucket-deltares-et/RA2CE-PTK;

    - name: ra2ce
      nodeSelector:
        spot: "true"
      inputs:
        parameters:
        - name: model
        artifacts:
        - name: model-input
          s3:
            bucket: bucket-deltares-et
            endpoint: s3.amazonaws.com
            key: "RA2CE-PTK/Ra2ce/KBN2_losses/{{inputs.parameters.model}}"
          archive:
            none: {}
          path: /data
        - name: static
          s3:
            bucket: bucket-deltares-et
            endpoint: s3.amazonaws.com
            key: "RA2CE-PTK/Ra2ce/KBN2_losses/static"
          archive:
            none: {}
          path: /static
      outputs:
        artifacts:
        - name: model-output
          s3:
            bucket: bucket-deltares-et
            endpoint: s3.amazonaws.com
            key: "RA2CE-PTK/Ra2ce/KBN2_losses/{{inputs.parameters.model}}/output"
          archive:
            none: {}
          path: /data/output
      container:
        image: deltares/ra2ce
        command:
          - python
        args:
          - run_with_args.py
          - /data/network.ini
          - /data/analyses.ini

      # Read all ra2ce input folders
    - name: read-models
      nodeSelector:
        kubernetes.io/os: linux
      script:
        image: "amazon/aws-cli:latest"
        command: [python]
        source: |
          import json
          data = ['data0']
          print(json.dumps(data))
        # aws s3 ls s3://bucket-deltares-et/RA2CE-PTK/Ra2ce/KBN2_losses/ | awk '{print $2}' | grep data[0-9]+* | sed 's:/*$::'
        
