FROM python:3.10

RUN apt-get update && apt-get install -y libgdal-dev

COPY .config/docker_requirements.txt requirements.txt
COPY ./infra/workflow/run_race.py ./script/run_race.py

RUN pip install -r ./requirements.txt

CMD ["python", "/script/run_race.py"]