---
name: New Release Request
description: Suggest a release for Ra2ce
labels: [enhancement, triage-required]
type: task
projects: [RA2CE backlog]

body:
  - type: dropdown
    id: checks
    attributes:
      description: >
        (Format `vMAJOR.Minor.patch`) 
        `MAJOR`, for (big) architectural changes are introduced or and upgrade of Python version occurs. 
        `Minor`, for new features.
        `patch`, for bug fixes and cleanup tasks.
      label: Kind of release
      options:
        - MAJOR
        - Minor
        - patch
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      description: >
        Please provide a clear and concise description of why this release is required
      label: Release Description
    validations:
      required: true