name: Bug Report
description: Report an incorrect behavior for Ra2ce.
labels: [Bug, Needs refinement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Ra2ce version checks
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have checked that this bug exists on the latest version of Ra2ce in `master` [here](https://github.com/Deltares/ra2ce).
          required: true
  - type: textarea
    id: example
    attributes:
      description: >
        Please provide a minimal example, whether as an attached file (Python file (`py`) or Jupyter notebook (`ipynb`)) or as text in this section.
      label: Reproducible example
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      description: >
        Please provide a description of the incorrect behaviour shown in the reproducible example.
      label: Current behaviour
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      description: >
        Please provide a description of what you think the behaviour should be.
      label: Desired behaviour
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      description: >
        Please add any other context about the bug here. For instance, the operating system or your python environment.
      label: Additional context
    validations:
      required: false