apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: ra2ce-hackathon-july-uq3-
spec:
  entrypoint: scenario-workflow
  arguments:
    parameters:
    - name: ra2ce_image
      value: containers.deltares.nl/ra2ce/ra2ce:hackathon_july_alpha
  templates:
  - name: scenario-workflow
    steps:
    - - name: check-ra2ce
        template: check-ra2ce
      - name: collect-hazard-cases
        template: collect-hazard-cases
    - - name: run-scenario
        template: run-script
        arguments:
          parameters:
          - name: hazard_name
            value: "{{item}}"
        withParam: "{{steps.collect-hazard-cases.outputs.result}}"
    - - name: post-process-data
        template: postprocess-script
  - name: collect-hazard-cases
    script:
      image: 798877697266.dkr.ecr.eu-west-1.amazonaws.com/boto3:latest
      command: [python, "/scripts/collect_hazard_data.py"]      
    inputs:
      artifacts:
        - name: exposure_and_od_analysis
          path: /exposure_and_od_analysis
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_july/working_dir
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_july/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
  - name: postprocess-script
    script:
      image: "{{workflow.parameters.ra2ce_image}}"
      command: [python, "/scripts/postprocess_output.py"]
      resources:
        requests:
          cpu: 1
          memory: "1Gi"
        limits:
          cpu: 1
          memory: "1Gi"
    nodeSelector:
      beta.kubernetes.io/instance-type: "t3.small"
    outputs:
      artifacts:
        - name: postprocess_results
          path: /postprocess_result
          s3: 
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: "hackathon_july/uq3_result_postprocess/"
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}     
    inputs:
      artifacts:
        - name: uq3_result_collection
          path: /uq3_results
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: "hackathon_july/uq3_results/"
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}          
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_july/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}  
  - name: run-script
    script:
      image: "{{workflow.parameters.ra2ce_image}}"
      command: [python, "/scripts/exposure_and_od_analysis.py"]
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
        limits:
          cpu: 1
          memory: "4Gi"
    nodeSelector:
      beta.kubernetes.io/instance-type: "m5.xlarge"
    outputs:
      artifacts:
        - name: result_exposure_and_od_analysis
          path: /exposure_and_od_analysis/output/multi_link_origin_closest_destination
          s3: 
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: "hackathon_july/uq3_results/{{inputs.parameters.hazard_name}}"
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}     
    inputs:
      parameters:
        - name: hazard_name
      artifacts:
        - name: selected_hazard_file
          path: "/exposure_and_od_analysis/hazard_files/{{inputs.parameters.hazard_name}}.tif"
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: "hackathon_july/hazard_files/{{inputs.parameters.hazard_name}}.tif"
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}          
        - name: exposure_and_od_analysis
          path: /exposure_and_od_analysis
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_july/working_dir
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_july/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
  
  - name: check-ra2ce
    script:
      image: "{{workflow.parameters.ra2ce_image}}"
      command: [python, "/scripts/check_ra2ce_version.py"]
    inputs: 
      artifacts:
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_july/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}