apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: ra2ce-uncertainty-uq2-
spec:
  entrypoint: scenario-workflow
  arguments:
    parameters:
      - name: ra2ce_image
        value: containers.deltares.nl/ra2ce/ra2ce:hackathon_july_local
  templates:
  - name: scenario-workflow
    steps:
    - - name: get-events-output-graphs
        template: get-events-output-graphs
      - name: check-ra2ce
        template: check-ra2ce
        arguments:
          parameters:
          - name: ra2ce_tag
            value: latest
    - - name: run-damage
        template: run-damage
        arguments:
          parameters:
          - name: ra2ce_tag
            value: latest
          - name: output_floodmap
            value: "{{item}}"
        withParam: "{{steps.get-events-output-graphs.outputs.result}}"
  - name: check-ra2ce
    script:
      image: "containers.deltares.nl/ra2ce/ra2ce_hackathon_dealing_with_uncertainty_poc:{{inputs.parameters.ra2ce_tag}}"
      command: [python, "/scripts/check_ra2ce_version.py"]
    inputs:
      parameters:
        - name: ra2ce_tag
      artifacts:
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_uncertainty/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}

  - name: get-events-output-graphs
    script:
      image: 798877697266.dkr.ecr.eu-west-1.amazonaws.com/boto3:latest
      workingDir: /modeldata
      command: [python, "/scripts/generate_event_scenarios.py"]
    inputs: 
      artifacts:
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_uncertainty/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}

  - name: run-damage
    container:
      image: "containers.deltares.nl/ra2ce/ra2ce_hackathon_dealing_with_uncertainty_poc:{{inputs.parameters.ra2ce_tag}}"
      command: [ sh, -c ]
      args:
        - |
          mkdir -p /modeldata/output && \
          mkdir -p /output_workflow2 && \
          python /scripts/workflow_damages.py
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
        limits:
          cpu: 1
          memory: "4Gi"
    nodeSelector:
      beta.kubernetes.io/instance-type: "m5.xlarge"
    inputs:
      parameters:
        - name: ra2ce_tag
        - name: output_floodmap
      artifacts:
        - name: output_graph_1
          path: /output_graph_1 # How we mount it.
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: "hackathon_uncertainty/output_1/{{inputs.parameters.output_floodmap}}"
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
        - name: vulnerability_curves
          path: /vulnerability_curves # How we mount it
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_uncertainty/vulnerability_curves
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
        - name: modeldata
          path: /modeldata # How we mount it.
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_uncertainty/working_dir
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: hackathon_uncertainty/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
    outputs:
      artifacts:
      - name: ra2ce-analysis-output
        path: /output_workflow2
        s3:
          bucket: ra2ce-data
          endpoint: s3.amazonaws.com
          region: eu-west-1
          key: hackathon_uncertainty/output_2/{{inputs.parameters.output_floodmap}}/{{pod.name}}
          accessKeySecret:
            name: my-s3-credentials
            key: accessKey
          secretKeySecret:
            name: my-s3-credentials
            key: secretKey
        archive:
          none: {}
