apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: ra2ce-uncertainty-uq1-
spec:
  entrypoint: scenario-workflow
  templates:
  - name: scenario-workflow
    steps:
    - - name: define-events
        template: get-events
    - - name: run-scenario
        template: run-scenario
        arguments:
          parameters:
          - name: event_floodmap
            value: "{{item}}"
        withParam: "{{steps.define-events.outputs.result}}"
    # - - name: post-processing
    #     template: post-processing

  - name: get-events
    script:
      image: containers.deltares.nl/ra2ce/ra2ce:hackathon_uncertainty
      workingDir: /modeldata
      command: [python]
      source: |
          import json
          from pathlib import Path

          import boto3

          # s3://ra2ce-data/uncertainty_hackathon/flood_maps/
          bucket = "ra2ce-data"
          _root_dir = "uncertainty_hackathon/flood_maps/"

          client = boto3.client("s3")
          result = client.list_objects(Bucket=bucket, Prefix=_root_dir, Delimiter="/")
          members = []
          for _sub_prefix in result.get("CommonPrefixes"):
              _prefix = _sub_prefix["Prefix"]
              _prefix_path = Path(_prefix)
              _prefix_result = client.list_objects(Bucket=bucket, Prefix=_prefix, Delimiter="/")
              _event_files = [
                  str(Path(_c["Key"]).relative_to(_prefix_path.parent))
                  for _c in _prefix_result.get("Contents")
              ]
              members.extend(_event_files)
          print(json.dumps(members))
  - name: run-scenario
    container:
      image: containers.deltares.nl/ra2ce/ra2ce:hackathon_uncertainty
      command: [python, "/scripts/workflow_hazard_overlay.py"]
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
        limits:
          cpu: 1
          memory: "4Gi"
    nodeSelector:
      beta.kubernetes.io/instance-type: "m5.xlarge"
    inputs:
      parameters:
        - name: event_floodmap
      artifacts:
        - name: events
          path: /events/{{inputs.parameters.event_floodmap}} # How we mount it.
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: "uncertainty_hackathon/flood_maps/{{inputs.parameters.event_floodmap}}"
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
        - name: modeldata
          path: /modeldata # How we mount it.
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: uncertainty_hackathon/working_dir
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
        - name: scripts
          path: /scripts
          s3:
            endpoint: s3.amazonaws.com
            bucket: ra2ce-data
            key: uncertainty_hackathon/scripts
            region: eu-west-1
            accessKeySecret:
              name: my-s3-credentials
              key: accessKey
            secretKeySecret:
              name: my-s3-credentials
              key: secretKey
          archive:
            none: {}
    outputs:
      artifacts:
      - name: ra2ce-output
        path: /modeldata
        s3:
          bucket: ra2ce-data
          endpoint: s3.amazonaws.com
          region: eu-west-1
          key: uncertainty_hackathon/output_1/{{inputs.parameters.event_floodmap}}/
          accessKeySecret:
            name: my-s3-credentials
            key: accessKey
          secretKeySecret:
            name: my-s3-credentials
            key: secretKey
        archive:
          none: {}

  # - name: post-processing
  #   container:
  #     image: containers.deltares.nl/ra2ce/ra2ce:latest
  #     command: ["python", "/scripts/user_question_1/post_processing.py"]
  #     #command: [sh, "-c", "for I in $(seq 1 1000) ; do echo $I ; sleep 1s; done"]
  #   nodeSelector:
  #     beta.kubernetes.io/instance-type: "m5.xlarge"
  #   inputs:
  #     artifacts:
  #       - name: output
  #         path: /data
  #         s3:
  #           endpoint: s3.amazonaws.com
  #           bucket: ra2ce-data
  #           key: beira_qualimane_sfincs_fm/output_q1
  #           region: eu-west-1
  #           accessKeySecret:
  #             name: my-s3-credentials
  #             key: accessKey
  #           secretKeySecret:
  #             name: my-s3-credentials
  #             key: secretKey
  #         archive:
  #           none: {}
  #       - name: scripts
  #         path: /scripts
  #         s3:
  #           endpoint: s3.amazonaws.com
  #           bucket: ra2ce-data
  #           key: beira_qualimane_sfincs_fm/scripts
  #           region: eu-west-1
  #           accessKeySecret:
  #             name: my-s3-credentials
  #             key: accessKey
  #           secretKeySecret:
  #             name: my-s3-credentials
  #             key: secretKey
  #         archive:
  #           none: {}
  #   outputs:
  #     artifacts:
  #       - name: pp_output
  #         path: /output
  #         s3:
  #           endpoint: s3.amazonaws.com
  #           bucket: ra2ce-data
  #           key: beira_qualimane_sfincs_fm/postprocessing_output_q1
  #           region: eu-west-1
  #           accessKeySecret:
  #             name: my-s3-credentials
  #             key: accessKey
  #           secretKeySecret:
  #             name: my-s3-credentials
  #             key: secretKey
  #         archive:
  #           none: {}
