name: ra2cedocs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::sphinx
  - conda-forge::jupytext
  - conda-forge::nbsphinx
  - conda-forge::myst-parser
  - conda-forge::sphinx-book-theme
  - conda-forge::sphinx-copybutton
  - conda-forge::sphinx_rtd_theme